### ISSUE TITLE
count admin gsuite

### ISSUE THREAD

**Issue by laster13** [88lex/safire#1]
Hello,
Thank you very much for your superb work. Just one question, do you absolutely have to be a gsuite administrator to be able to use your project? is it possible by simply having a user account to be able to use it
thank you (sorry for my english i m french)

**Comment by 88lex** [comment]
Hello laster,
Thank you for the kind words.

In fact you do not need to be a gsuite administrator. You can create projects, service accounts, json keys, team/shared drives and add users to shared drives without being a gsuite super admin.

The only function for which you need to be a gsuite admin is to auto-add emails (including service account emails) to a group. This is also (sadly) required to use the Bulk Add feature in the Google Admin UI.

You are still able to add service account emails to groups, 100 at a time manually in the Groups web UI. And then add the group to your shared drive.  For many people this is sufficient.

**Comment by laster13** [comment]
thanks very much, i ll try

**Comment by laster13** [comment]
does it also work with my drive, not just with the team / shared drive?
thanks
