### ISSUE TITLE
Error while running ./safire.py auth projects

### ISSUE THREAD

**Issue by jepcd** [88lex/safire#3]
So I've just placed the creds.json file into the creds folder and when I run ./safire.py auth projects I get this error:

Traceback (most recent call last):
  File "safire.py", line 692, in <module>
    main()
  File "safire.py", line 688, in main
    fire.Fire(Commands)
  File "/home/alakh/.local/lib/python3.8/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/alakh/.local/lib/python3.8/site-packages/fire/core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/alakh/.local/lib/python3.8/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/alakh/Desktop/safire/safire/utils.py", line 128, in projects
    self.get_token(credentials, self.scopes_proj, token)
  File "/home/alakh/Desktop/safire/safire/utils.py", line 154, in get_token
    flow = InstalledAppFlow.from_client_secrets_file(cred_file[0], scopes)
IndexError: list index out of range

**Comment by twilson90** [comment]
Encountering the same error.

Why is this issue closed?

**Comment by twilson90** [comment]
Had a look at the code, this whole bit at the beginning of safire.py is just... weird:

```
if os.path.exists(cfg_file):
    copyfile(cfg_file, "config.py")
elif os.path.exists("config.py"):
    copyfile("config.py", cfg_file)
elif os.path.exists("default_config.py"):
    copyfile("default_config.py", "config.py")
    copyfile("default_config.py", cfg_file)
else:
    print("No config.py file found! Create a file config.py using the template at \n")
    print("https://github.com/88lex/safire/blob/master/safire/default_config.py\n")
    print("and paste it in your home/safire directory\n")
    exit()
import config as cf
```

I presume copyfile is trying to replace the config.py in the site-packages/safire/ folder, however all it's doing is copying config.py to my user directory (or whatever is my cwd)

Also not sure what this is supposed to do:

```sys.path.append("..")```

**Comment by BRTPOB** [comment]
Using hedgehog90's safire.py worked for me, so thanks @hedgehog90.
